/** Sample risks created during onboarding when the Risks list is empty. */
export const ASSET_SEED_DATA: Record<string, string>[] = [
  {
    Title: 'Third-party vendor data breach',
    RiskCategoryTitle: 'Technology',
    RiskSubCategoryTitle: 'Cybersecurity',
    BusinessTitle: 'Marketing',
    ProjectTitle: 'Digital Transformation',
    RiskProfileTypeTitle: 'Threat',
    RiskResponseTitle: 'Mitigation',
    RiskStrategyTitle: 'Accept',
    AM_Status: 'Open',
    Likelihood: '(4) Likely',
    Consequence: '(4) Major',
    PotentialLikelihood: '(2) Unlikely',
    PotentialConsequence: '(3) Moderate',
    potentialcost: '250000',
    Assesstheeffectivenessofcontrols: 'Fair',
    DateRiskIdentified: '2025-11-01',
    RiskDueDate: '2026-08-15'
  },
  {
    Title: 'Regulatory reporting deadline missed',
    RiskCategoryTitle: 'Compliance',
    RiskSubCategoryTitle: 'Regulatory',
    BusinessTitle: 'Finance',
    ProjectTitle: 'GDPR Compliance Initiative',
    RiskProfileTypeTitle: 'Threat',
    RiskResponseTitle: 'Avoidance',
    RiskStrategyTitle: 'Accept',
    AM_Status: 'In Progress',
    Likelihood: '(3) Possible',
    Consequence: '(5) Critical',
    PotentialLikelihood: '(2) Unlikely',
    PotentialConsequence: '(4) Major',
    potentialcost: '180000',
    Assesstheeffectivenessofcontrols: 'Good',
    DateRiskIdentified: '2025-09-12',
    RiskDueDate: '2026-06-30'
  },
  {
    Title: 'Critical system outage during peak season',
    RiskCategoryTitle: 'Operational',
    RiskSubCategoryTitle: 'System Failure',
    BusinessTitle: 'Sales',
    ProjectTitle: 'Cyber Security Enhancement',
    RiskProfileTypeTitle: 'Threat',
    RiskResponseTitle: 'Contingency',
    RiskStrategyTitle: 'Transfer',
    AM_Status: 'Open',
    Likelihood: '(3) Possible',
    Consequence: '(4) Major',
    PotentialLikelihood: '(2) Unlikely',
    PotentialConsequence: '(3) Moderate',
    potentialcost: '420000',
    Assesstheeffectivenessofcontrols: 'Poor',
    DateRiskIdentified: '2025-10-05',
    RiskDueDate: '2026-09-01'
  },
  {
    Title: 'Foreign exchange exposure on major contract',
    RiskCategoryTitle: 'Financial',
    RiskSubCategoryTitle: 'Currency Risk',
    BusinessTitle: 'Finance',
    ProjectTitle: 'Budget Planning 2026',
    RiskProfileTypeTitle: 'Threat',
    RiskResponseTitle: 'Transfer',
    RiskStrategyTitle: 'Accept',
    AM_Status: 'Open',
    Likelihood: '(4) Likely',
    Consequence: '(3) Moderate',
    PotentialLikelihood: '(3) Possible',
    PotentialConsequence: '(2) Minor',
    potentialcost: '95000',
    Assesstheeffectivenessofcontrols: 'Good',
    DateRiskIdentified: '2025-08-20',
    RiskDueDate: '2026-12-31'
  },
  {
    Title: 'Supply chain disruption for key materials',
    RiskCategoryTitle: 'Operational',
    RiskSubCategoryTitle: 'Supply Chain',
    BusinessTitle: 'Procurement',
    ProjectTitle: 'Internal Audit Program',
    RiskProfileTypeTitle: 'Threat',
    RiskResponseTitle: 'Mitigation',
    RiskStrategyTitle: 'Accept',
    AM_Status: 'In Progress',
    Likelihood: '(2) Unlikely',
    Consequence: '(4) Major',
    PotentialLikelihood: '(1) Rare',
    PotentialConsequence: '(3) Moderate',
    potentialcost: '310000',
    Assesstheeffectivenessofcontrols: 'Fair',
    DateRiskIdentified: '2025-07-14',
    RiskDueDate: '2026-05-20'
  },
  {
    Title: 'Cloud migration cost overrun',
    RiskCategoryTitle: 'Technology',
    RiskSubCategoryTitle: 'Third Party',
    BusinessTitle: 'Marketing',
    ProjectTitle: 'Digital Transformation',
    RiskProfileTypeTitle: 'Threat',
    RiskResponseTitle: 'Mitigation',
    RiskStrategyTitle: 'Closed',
    AM_Status: 'Closed',
    Likelihood: '(3) Possible',
    Consequence: '(3) Moderate',
    PotentialLikelihood: '(2) Unlikely',
    PotentialConsequence: '(2) Minor',
    potentialcost: '75000',
    Assesstheeffectivenessofcontrols: 'Good',
    DateRiskIdentified: '2024-12-01',
    RiskDueDate: '2025-06-30'
  },
  {
    Title: 'New market expansion opportunity',
    RiskCategoryTitle: 'Strategic',
    BusinessTitle: 'Sales',
    ProjectTitle: 'Cyber Security Enhancement',
    RiskProfileTypeTitle: 'Opportunity',
    RiskResponseTitle: 'Acceptance',
    RiskStrategyTitle: 'Accept',
    AM_Status: 'Open',
    Likelihood: '(3) Possible',
    Consequence: '(2) Minor',
    PotentialLikelihood: '(4) Likely',
    PotentialConsequence: '(3) Moderate',
    potentialcost: '50000',
    Assesstheeffectivenessofcontrols: 'Good',
    DateRiskIdentified: '2026-01-10',
    RiskDueDate: '2026-11-30'
  },
  {
    Title: 'Privacy incident from misconfigured access',
    RiskCategoryTitle: 'Technology',
    RiskSubCategoryTitle: 'Data Privacy',
    BusinessTitle: 'Marketing',
    ProjectTitle: 'ISO 27001 Compliance Program',
    RiskProfileTypeTitle: 'Threat',
    RiskResponseTitle: 'Mitigation',
    RiskStrategyTitle: 'Accept',
    AM_Status: 'Open',
    Likelihood: '(2) Unlikely',
    Consequence: '(5) Critical',
    PotentialLikelihood: '(1) Rare',
    PotentialConsequence: '(3) Moderate',
    potentialcost: '520000',
    Assesstheeffectivenessofcontrols: 'Fair',
    DateRiskIdentified: '2025-12-18',
    RiskDueDate: '2026-07-01'
  },
  {
    Title: 'Payroll processing error',
    RiskCategoryTitle: 'Operational',
    RiskSubCategoryTitle: 'Human Error',
    BusinessTitle: 'Finance',
    ProjectTitle: 'Budget Planning 2026',
    RiskProfileTypeTitle: 'Threat',
    RiskResponseTitle: 'Mitigation',
    RiskStrategyTitle: 'Accept',
    AM_Status: 'Open',
    Likelihood: '(3) Possible',
    Consequence: '(4) Major',
    PotentialLikelihood: '(2) Unlikely',
    PotentialConsequence: '(3) Moderate',
    potentialcost: '85000',
    Assesstheeffectivenessofcontrols: 'Fair',
    DateRiskIdentified: 'REL:-45d',
    RiskDueDate: 'REL:-10d'
  },
  {
    Title: 'Vendor SLA breach escalation',
    RiskCategoryTitle: 'Operational',
    RiskSubCategoryTitle: 'Supply Chain',
    BusinessTitle: 'Procurement',
    ProjectTitle: 'Internal Audit Program',
    RiskProfileTypeTitle: 'Threat',
    RiskResponseTitle: 'Contingency',
    RiskStrategyTitle: 'Transfer',
    AM_Status: 'In Progress',
    Likelihood: '(4) Likely',
    Consequence: '(3) Moderate',
    PotentialLikelihood: '(2) Unlikely',
    PotentialConsequence: '(2) Minor',
    potentialcost: '120000',
    Assesstheeffectivenessofcontrols: 'Poor',
    DateRiskIdentified: 'REL:-30d',
    RiskDueDate: 'REL:-3d',
    AssignToCurrentUser: 'true'
  },
  {
    Title: 'Firewall rule review overdue',
    RiskCategoryTitle: 'Technology',
    RiskSubCategoryTitle: 'Cybersecurity',
    BusinessTitle: 'Sales',
    ProjectTitle: 'Cyber Security Enhancement',
    RiskProfileTypeTitle: 'Threat',
    RiskResponseTitle: 'Mitigation',
    RiskStrategyTitle: 'Accept',
    AM_Status: 'Open',
    Likelihood: '(2) Unlikely',
    Consequence: '(5) Critical',
    PotentialLikelihood: '(1) Rare',
    PotentialConsequence: '(3) Moderate',
    potentialcost: '275000',
    Assesstheeffectivenessofcontrols: 'Fair',
    DateRiskIdentified: 'REL:-60d',
    RiskDueDate: 'REL:-14d',
    AssignToCurrentUser: 'true'
  },
  {
    Title: 'Board report submission deadline',
    RiskCategoryTitle: 'Compliance',
    RiskSubCategoryTitle: 'Regulatory',
    BusinessTitle: 'Finance',
    ProjectTitle: 'GDPR Compliance Initiative',
    RiskProfileTypeTitle: 'Threat',
    RiskResponseTitle: 'Avoidance',
    RiskStrategyTitle: 'Accept',
    AM_Status: 'In Progress',
    Likelihood: '(3) Possible',
    Consequence: '(4) Major',
    PotentialLikelihood: '(2) Unlikely',
    PotentialConsequence: '(3) Moderate',
    potentialcost: '65000',
    Assesstheeffectivenessofcontrols: 'Good',
    DateRiskIdentified: 'REL:-20d',
    RiskDueDate: 'REL:+0d'
  },
  {
    Title: 'Staff safety briefing completion',
    RiskCategoryTitle: 'Health & Safety',
    BusinessTitle: 'Procurement',
    ProjectTitle: 'Internal Audit Program',
    RiskProfileTypeTitle: 'Threat',
    RiskResponseTitle: 'Mitigation',
    RiskStrategyTitle: 'Accept',
    AM_Status: 'Open',
    Likelihood: '(3) Possible',
    Consequence: '(3) Moderate',
    PotentialLikelihood: '(2) Unlikely',
    PotentialConsequence: '(2) Minor',
    potentialcost: '15000',
    Assesstheeffectivenessofcontrols: 'Good',
    DateRiskIdentified: 'REL:-14d',
    RiskDueDate: 'REL:+0d',
    AssignToCurrentUser: 'true'
  },
  {
    Title: 'Contract renewal decision pending',
    RiskCategoryTitle: 'Legal',
    RiskSubCategoryTitle: 'Contractual',
    BusinessTitle: 'Sales',
    ProjectTitle: 'Digital Transformation',
    RiskProfileTypeTitle: 'Threat',
    RiskResponseTitle: 'Acceptance',
    RiskStrategyTitle: 'Accept',
    AM_Status: 'Open',
    Likelihood: '(2) Unlikely',
    Consequence: '(3) Moderate',
    PotentialLikelihood: '(1) Rare',
    PotentialConsequence: '(2) Minor',
    potentialcost: '40000',
    Assesstheeffectivenessofcontrols: 'Good',
    DateRiskIdentified: 'REL:-10d',
    RiskDueDate: 'REL:+2d'
  },
  {
    Title: 'Quarterly audit walkthrough',
    RiskCategoryTitle: 'Compliance',
    RiskSubCategoryTitle: 'Internal Policy',
    BusinessTitle: 'Finance',
    ProjectTitle: 'Internal Audit Program',
    RiskProfileTypeTitle: 'Threat',
    RiskResponseTitle: 'Mitigation',
    RiskStrategyTitle: 'Accept',
    AM_Status: 'In Progress',
    Likelihood: '(3) Possible',
    Consequence: '(3) Moderate',
    PotentialLikelihood: '(2) Unlikely',
    PotentialConsequence: '(2) Minor',
    potentialcost: '22000',
    Assesstheeffectivenessofcontrols: 'Fair',
    DateRiskIdentified: 'REL:-7d',
    RiskDueDate: 'REL:+4d',
    AssignToCurrentUser: 'true'
  },
  {
    Title: 'Insurance certificate update',
    RiskCategoryTitle: 'Financial',
    RiskSubCategoryTitle: 'Credit Risk',
    BusinessTitle: 'Finance',
    ProjectTitle: 'Budget Planning 2026',
    RiskProfileTypeTitle: 'Threat',
    RiskResponseTitle: 'Transfer',
    RiskStrategyTitle: 'Transfer',
    AM_Status: 'Open',
    Likelihood: '(2) Unlikely',
    Consequence: '(4) Major',
    PotentialLikelihood: '(1) Rare',
    PotentialConsequence: '(3) Moderate',
    potentialcost: '180000',
    Assesstheeffectivenessofcontrols: 'Good',
    DateRiskIdentified: 'REL:-5d',
    RiskDueDate: 'REL:+6d'
  },
  {
    Title: 'Legacy system decommission sign-off',
    RiskCategoryTitle: 'Technology',
    RiskSubCategoryTitle: 'System Failure',
    BusinessTitle: 'Marketing',
    ProjectTitle: 'Digital Transformation',
    RiskProfileTypeTitle: 'Threat',
    RiskResponseTitle: 'Mitigation',
    RiskStrategyTitle: 'Closed',
    AM_Status: 'Closed',
    Likelihood: '(2) Unlikely',
    Consequence: '(3) Moderate',
    PotentialLikelihood: '(1) Rare',
    PotentialConsequence: '(1) Insignificant',
    potentialcost: '35000',
    Assesstheeffectivenessofcontrols: 'Good',
    DateRiskIdentified: 'REL:-90d',
    RiskDueDate: 'REL:-30d'
  },
  {
    Title: 'Phishing awareness campaign wrap-up',
    RiskCategoryTitle: 'Technology',
    RiskSubCategoryTitle: 'Cybersecurity',
    BusinessTitle: 'Marketing',
    ProjectTitle: 'ISO 27001 Compliance Program',
    RiskProfileTypeTitle: 'Threat',
    RiskResponseTitle: 'Mitigation',
    RiskStrategyTitle: 'Closed',
    AM_Status: 'Closed',
    Likelihood: '(3) Possible',
    Consequence: '(2) Minor',
    PotentialLikelihood: '(2) Unlikely',
    PotentialConsequence: '(1) Insignificant',
    potentialcost: '8000',
    Assesstheeffectivenessofcontrols: 'Good',
    DateRiskIdentified: 'REL:-45d',
    RiskDueDate: 'REL:+0d'
  },
  {
    Title: 'Warehouse inventory mismatch',
    RiskCategoryTitle: 'Operational',
    RiskSubCategoryTitle: 'Process Failure',
    BusinessTitle: 'Procurement',
    ProjectTitle: 'Internal Audit Program',
    RiskProfileTypeTitle: 'Threat',
    RiskResponseTitle: 'Contingency',
    RiskStrategyTitle: 'Accept',
    AM_Status: 'Open',
    Likelihood: '(3) Possible',
    Consequence: '(3) Moderate',
    PotentialLikelihood: '(2) Unlikely',
    PotentialConsequence: '(2) Minor',
    potentialcost: '55000',
    Assesstheeffectivenessofcontrols: 'Fair',
    DateRiskIdentified: 'REL:-21d',
    RiskDueDate: 'REL:+45d',
    AssignToCurrentUser: 'true'
  },
  {
    Title: 'Partner integration delivery delay',
    RiskCategoryTitle: 'Strategic',
    BusinessTitle: 'Sales',
    ProjectTitle: 'Cyber Security Enhancement',
    RiskProfileTypeTitle: 'Opportunity',
    RiskResponseTitle: 'Acceptance',
    RiskStrategyTitle: 'Accept',
    AM_Status: 'In Progress',
    Likelihood: '(4) Likely',
    Consequence: '(2) Minor',
    PotentialLikelihood: '(3) Possible',
    PotentialConsequence: '(3) Moderate',
    potentialcost: '70000',
    Assesstheeffectivenessofcontrols: 'Good',
    DateRiskIdentified: 'REL:-12d',
    RiskDueDate: 'REL:+60d'
  }
];
