/** Sample assets created during onboarding when sample data is enabled. */
export const ASSET_SEED_DATA: Record<string, string | number | boolean>[] = [
  {
    Title: 'Dell Latitude 5540 — Finance Pool',
    ImageSeedKey: 'laptop',
    CategoryTitle: 'IT Hardware',
    SubCategoryTitle: 'Laptops',
    AssetTypeTitle: 'Laptop',
    StatusTitle: 'Available',
    VendorTitle: 'Dell Technologies',
    LocationTitle: 'Head Office',
    ProjectTitle: 'Office Refresh 2026',
    AM_SerialNumber: 'SN-DL-5540-001',
    AM_Barcode: 'BC-10001',
    AM_Cost: 1899,
    AM_PurchaseDate: '2025-06-15',
    AM_WarrantyExpiry: '2028-06-15',
    AM_Manufacturer: 'Dell',
    AM_OS: 'Windows 11',
    AM_CPU: 'Intel Core i7-1355U',
    AM_TotalMemory: '16 GB',
    AM_Storage: '512 GB SSD'
  },
  {
    Title: 'MacBook Pro 14 — Marketing',
    ImageSeedKey: 'laptop',
    CategoryTitle: 'IT Hardware',
    SubCategoryTitle: 'Laptops',
    AssetTypeTitle: 'Laptop',
    StatusTitle: 'Assigned',
    VendorTitle: 'Apple',
    LocationTitle: 'Head Office',
    ProjectTitle: 'Remote Worker Kit',
    AM_SerialNumber: 'SN-MBP-14-002',
    AM_Barcode: 'BC-10002',
    AM_Cost: 2499,
    AM_PurchaseDate: '2025-08-01',
    AM_WarrantyExpiry: '2028-08-01',
    AM_Manufacturer: 'Apple',
    AM_OS: 'macOS',
    AM_TotalMemory: '16 GB',
    AM_Storage: '512 GB SSD',
    AssignToCurrentUser: 'true'
  },
  {
    Title: 'Dell UltraSharp 27 Monitor',
    ImageSeedKey: 'monitor',
    CategoryTitle: 'IT Hardware',
    SubCategoryTitle: 'Monitors',
    AssetTypeTitle: 'Monitor',
    StatusTitle: 'Available',
    VendorTitle: 'Dell Technologies',
    LocationTitle: 'Head Office',
    ProjectTitle: 'Office Refresh 2026',
    AM_SerialNumber: 'SN-U2723-003',
    AM_Barcode: 'BC-10003',
    AM_Cost: 649,
    AM_PurchaseDate: '2025-05-20',
    AM_WarrantyExpiry: '2028-05-20',
    AM_Manufacturer: 'Dell'
  },
  {
    Title: 'Lenovo ThinkCentre M90 — Reception',
    ImageSeedKey: 'desktop',
    CategoryTitle: 'IT Hardware',
    SubCategoryTitle: 'Desktops',
    AssetTypeTitle: 'Desktop',
    StatusTitle: 'Available',
    VendorTitle: 'Dell Technologies',
    LocationTitle: 'Head Office',
    ProjectTitle: 'Office Refresh 2026',
    AM_SerialNumber: 'SN-TC-M90-004',
    AM_Barcode: 'BC-10004',
    AM_Cost: 1199,
    AM_PurchaseDate: '2025-04-10',
    AM_WarrantyExpiry: '2028-04-10',
    AM_Manufacturer: 'Lenovo',
    AM_OS: 'Windows 11'
  },
  {
    Title: 'iPhone 15 — Sales Demo Kit',
    ImageSeedKey: 'phone',
    CategoryTitle: 'IT Hardware',
    SubCategoryTitle: 'Mobile Devices',
    AssetTypeTitle: 'Phone',
    StatusTitle: 'Assigned',
    VendorTitle: 'Apple',
    LocationTitle: 'Remote / Home',
    ProjectTitle: 'Remote Worker Kit',
    AM_SerialNumber: 'SN-IP15-005',
    AM_IMEI: '356938035643809',
    AM_Cost: 999,
    AM_PurchaseDate: '2025-09-01',
    AM_WarrantyExpiry: '2026-09-01',
    AM_Manufacturer: 'Apple',
    AM_OS: 'iOS',
    AssignToCurrentUser: 'true'
  },
  {
    Title: 'Surface Pro 9 — Warehouse Scanner',
    ImageSeedKey: 'tablet',
    CategoryTitle: 'IT Hardware',
    SubCategoryTitle: 'Mobile Devices',
    AssetTypeTitle: 'Tablet',
    StatusTitle: 'In Repair',
    VendorTitle: 'Microsoft',
    LocationTitle: 'Warehouse',
    ProjectTitle: 'Legacy Decommission',
    AM_SerialNumber: 'SN-SP9-006',
    AM_Barcode: 'BC-10006',
    AM_Cost: 1399,
    AM_PurchaseDate: '2024-11-15',
    AM_WarrantyExpiry: '2027-11-15',
    AM_Manufacturer: 'Microsoft',
    AM_OS: 'Windows 11',
    AM_Notes: 'Screen replacement scheduled.'
  },
  {
    Title: 'HP LaserJet Pro — Floor 2',
    ImageSeedKey: 'printer',
    CategoryTitle: 'IT Hardware',
    SubCategoryTitle: 'Desktops',
    AssetTypeTitle: 'Other',
    StatusTitle: 'Available',
    VendorTitle: 'Dell Technologies',
    LocationTitle: 'Head Office',
    AM_SerialNumber: 'SN-HP-LJ-007',
    AM_Cost: 449,
    AM_PurchaseDate: '2023-02-01',
    AM_WarrantyExpiry: '2026-02-01',
    AM_Manufacturer: 'HP'
  },
  {
    Title: 'Standing Desk — Meeting Room A',
    ImageSeedKey: 'furniture',
    CategoryTitle: 'Furniture',
    SubCategoryTitle: 'Desks & Tables',
    AssetTypeTitle: 'Other',
    StatusTitle: 'Available',
    LocationTitle: 'Head Office',
    ProjectTitle: 'Office Refresh 2026',
    AM_Barcode: 'BC-20001',
    AM_Cost: 890,
    AM_PurchaseDate: '2025-03-01',
    AM_Notes: 'Electric height-adjustable desk.'
  },
  {
    Title: 'Ergonomic Chair — Hot Desk 3',
    ImageSeedKey: 'furniture',
    CategoryTitle: 'Furniture',
    SubCategoryTitle: 'Chairs',
    AssetTypeTitle: 'Other',
    StatusTitle: 'Available',
    LocationTitle: 'Head Office',
    AM_Barcode: 'BC-20002',
    AM_Cost: 650,
    AM_PurchaseDate: '2025-03-01'
  },
  {
    Title: 'Company Van — Fleet 01',
    ImageSeedKey: 'vehicle',
    CategoryTitle: 'Vehicles',
    AssetTypeTitle: 'Other',
    StatusTitle: 'Assigned',
    LocationTitle: 'Warehouse',
    ProjectTitle: 'Legacy Decommission',
    AM_SerialNumber: 'VIN-1HGBH41JXMN109186',
    AM_Cost: 32000,
    AM_PurchaseDate: '2022-06-01',
    AM_Notes: 'Registration renewal due Q4.',
    AssignToCurrentUser: 'true'
  },
  {
    Title: 'Windows Server 2022 — DEV-01',
    ImageSeedKey: 'server',
    CategoryTitle: 'IT Hardware',
    SubCategoryTitle: 'Desktops',
    AssetTypeTitle: 'Server',
    StatusTitle: 'Retired',
    VendorTitle: 'Microsoft',
    LocationTitle: 'Warehouse',
    ProjectTitle: 'Legacy Decommission',
    AM_SerialNumber: 'SN-WS-DEV-011',
    AM_Cost: 8500,
    AM_PurchaseDate: '2020-01-15',
    AM_WarrantyExpiry: '2023-01-15',
    AM_Manufacturer: 'Dell',
    AM_OS: 'Windows Server 2022'
  },
  {
    Title: 'Microsoft 365 E3 (Seat Bundle)',
    ImageSeedKey: 'software',
    CategoryTitle: 'Software',
    SubCategoryTitle: 'Productivity Suite',
    AssetTypeTitle: 'License',
    StatusTitle: 'Available',
    VendorTitle: 'Microsoft',
    LocationTitle: 'Head Office',
    ProjectTitle: 'Office Refresh 2026',
    AM_Cost: 240,
    AM_PurchaseDate: '2025-01-01',
    AM_WarrantyExpiry: '2027-01-15',
    AM_Notes: 'Linked to AM_SoftwareLicenses pool record.'
  }
];
