/** Non-hidden Risks list fields used to validate load-field coverage in unit tests. */
export const RISK_DEFINITION_LOAD_FIELDS = [
  { internalName: 'RiskDescription', type: 'Note' },
  { internalName: 'Riskstatus', type: 'Choice' },
  { internalName: 'AssignedTo', type: 'UserMulti' },
  { internalName: 'RiskComment', type: 'Note' },
  { internalName: 'RiskID', type: 'Text' },
  { internalName: 'OldAssigneeId', type: 'Text', hidden: true },
  { internalName: 'RiskDueDate', type: 'DateTime' },
  { internalName: 'MitigationPlan', type: 'Note' },
  { internalName: 'RiskResponse', type: 'Lookup' },
  { internalName: 'RiskStrategy', type: 'Lookup' },
  { internalName: 'RiskProfileType', type: 'Lookup' },
  { internalName: 'Likelihood', type: 'Choice' },
  { internalName: 'Consequence', type: 'Choice' },
  { internalName: 'PotentialLikelihood', type: 'Choice' },
  { internalName: 'PotentialConsequence', type: 'Choice' },
  { internalName: 'potentialcost', type: 'Text' },
  { internalName: 'Assesstheeffectivenessofcontrols', type: 'Choice' },
  { internalName: 'Implementationreviewdate', type: 'DateTime' },
  { internalName: 'DateRiskIdentified', type: 'DateTime' },
  { internalName: 'RiskCategory', type: 'Lookup' },
  { internalName: 'RiskSubCategory', type: 'Lookup' },
  { internalName: 'riskBusiness', type: 'Lookup' },
  { internalName: 'RiskProject', type: 'Lookup' },
  { internalName: 'ProjectName', type: 'Text' },
  { internalName: 'Causes', type: 'Note' },
  { internalName: 'RiskConsequences', type: 'Note' },
  { internalName: 'ExistingControls', type: 'Note' },
  { internalName: 'RelatedRisks', type: 'LookupMulti' },
  { internalName: 'TemplateData', type: 'Note', hidden: true }
] as const;
